/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc

fun main() {
    println("AoC 2022:")

    println("Day 1 part 1 solution:")
    println(mostCals())  // 70374
    println("Day 1 part 2 solution:")
    println(top3Sum())  // 204610


    println("Day 2 part 1 solution:")
    println(totalScore())
}
